function PHI = calcPHI(wx,wy,wz)
%CALCPHI
%    PHI = CALCPHI(WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    20-Jan-2018 16:51:31

t2 = wz.*(1.0./2.0);
t3 = wx.*(1.0./2.0);
t4 = wy.*(1.0./2.0);
PHI = reshape([1.0,t3,t4,t2,0.0,0.0,0.0,wx.*(-1.0./2.0),1.0,-t2,t4,0.0,0.0,0.0,wy.*(-1.0./2.0),t2,1.0,-t3,0.0,0.0,0.0,wz.*(-1.0./2.0),wy.*(-1.0./2.0),t3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[7, 7]);
