function PHI = calcPHI(wx,wy,wz)
%CALCPHI
%    PHI = CALCPHI(WX,WY,WZ)

%    This function was generated by the Symbolic Math Toolbox version 6.0.
%    01-Feb-2018 17:34:37

PHI = reshape([-1.0,-wz,wy,0.0,0.0,0.0,wz,-1.0,-wx,0.0,0.0,0.0,-wy,wx,-1.0,0.0,0.0,0.0,-1.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,1.0,0.0,0.0,0.0,-1.0,0.0,0.0,1.0],[6, 6]);
